<!DOCTYPE html>
<html>
<head>
<meta charset='utf-8' />
<?php
    require_once("inc/stdLib.php");
    include("inc/crmLib.php");
    $menu = $_SESSION['menu'];
    $head = mkHeader();
    echo $menu['stylesheets'];
    echo $head['FULLCALCSS'];
    echo $head['BOXCSS'];
    echo $head['JQUERY'];   
    echo $head['JQUERYUI'];
    echo $head['THEME'];
    echo $head['FULLCALJS'];
    echo $head['JQBOX'];
    //print_r( $_SESSION );

?>


<script>

	$(document).ready(function() {
        var id = 0;
        $( "#dialog" ).dialog({
            autoOpen: false,
            height: 500 ,
            width: 680,
            modal: true,
            buttons: {
                "Save": function() {
                    var start = moment($( "#startDate" ).val() + ' ' + $( "#startTime" ).val(),'L LT');
                    var end = moment($( "#endDate" ).val() + ' ' + $( "#endTime" ).val(),'L LT');
                    var start_cur = moment($( "#startDate" ).val() + ' ' + $( "#startTime" ).val(),'L LT').add('h', 2);
                    var end_cur = moment($( "#endDate" ).val() + ' ' + $( "#endTime" ).val(),'L LT').add('h', 2);
                    var title = $( "#title" ).val();
                    var desc = $( "#desc" ).val();
                    var id = $( "#id" ).val();
                    if ( title ) {
				    event = {
						title: title,
						start: start_cur,
						end: end_cur,
						id : id,
						desc: desc
					} 
                    start = moment(start).format( "YYYY-MM-DD HH:mm:ss");
                    end = moment(end).format( "YYYY-MM-DD HH:mm:ss");
                    $.ajax({
                        url: 'jqhelp/calendar.php',
                        data: {
                            task:  $("#id").val() ? 'updateEvent' : 'newEvent', 
                            title: $("#title").val(),
                            desc: $("#desc").val(),
                            id:   $("#id").val(),
                            start: start,
                            end: end
                        },
                        type: "POST",
                        success: function(lastid) {
                            //var text = id ? 'Event updated' : 'Event added';
                            //alert( text + "LastID: " + lastid );
                            if( !$("#id").val() ){
                                $( "#id" ).val(lastid);
                                id = lastid;
                                //event.id = lastid;
                            }
                            //$('#calendar').fullCalendar('rerenderEvents')
                        },
                        error: function () {
                            alert('Ajax Error');
                        }
                    })
                    
                    //if( event.id ) $('#calendar').fullCalendar('removeEvents', event.id);// Wenn keine id dann hier letzte id holen
                    ///$('#calendar').fullCalendar('renderEvent', event)
                    $('#calendar').fullCalendar("refetchEvents");//!!!doof ist dass alle Events neu geholt werden!!!!
                
                //$('#calendar').fullCalendar('unselect');
                
				}
			    else alert('Title is empty');                  
                $( this ).dialog( "close" );
                },
                Delete: function() { 
                    var id = $( "#id" ).val(); 
                       
                    if( id ) $('#calendar').fullCalendar('removeEvents', id);                
                    $.ajax({
                        url: 'jqhelp/calendar.php',
                        data: {
                            task:  'deleteEvent',
                            id: $("#id").val() 
                        },
                        type: "POST",
                        success: function() {
                            //alert( "Event gelöscht"  );
                        },
                        error: function () {
                            alert('Ajax Error');
                        }
                    }) 
                    //$('#calendar').fullCalendar('rerenderEvents')  
                    //$('#calendar').fullCalendar('renderEvent', event)          
                    $( this ).dialog( "close" );
                },
                Cancel: function() {                         
                    $( this ).dialog( "close" );
                }
            },
            close: function() {                       
                $( this ).dialog( "close" );
            }

        });

		$('#calendar').fullCalendar({
		    theme: true,
			header: {
				left: 'prev,next today',
				center: 'title, test',
				right: 'month,agendaWeek,agendaDay'
			},
			minTime: '<?php echo $_SESSION['termbegin'] ? $_SESSION['termbegin'] : 7;echo ":00"; ?>',
			maxTime: '<?php echo $_SESSION['termend'] ? $_SESSION['termend'] : 19; echo ":00"; ?>',
			slotDuration: '<?php echo "00:";echo $_SESSION['termseq'] ? $_SESSION['termseq'] : 30; echo ":00"; ?>', //termseq
			weekNumbers: true,
			editable: true,
		    eventClick: function(event) {
		        
		        $("#title").val(event.title);
		        $("#desc").val(event.desc);
		        if( event.id ) $( "#id" ).val( event.id );//$( "#id" ).val()
		        //moment.lang('en');
		        $( "#startDate" ).val( moment( event.start ).format( "L") );
		        $( "#startTime" ).val( moment( event.start ).format( "LT") );
		        $( "#endDate" ).val( moment( event.end ).format( "L") );
		        $( "#endTime" ).val( moment( event.end ).format( "LT") );
		        
		        //alert(  " ID: " +  event.id );
			     $( "#dialog" ).dialog( "open" );
				 return false;
			},
			defaultView: 'agendaWeek',
			dragble: true,
			selectable: true,    
			selectHelper: true,
			select: function(start, end) {
				$( "#title" ).val('');
				$( "#desc" ).val('');
				$( "#id" ).val('');
		        $( "#startDate" ).val( moment( start ).format( "L") );
		        $( "#startTime" ).val( moment( start ).format( "LT") );
		        $( "#endDate" ).val( moment( end ).format( "L") );
		        $( "#endTime" ).val( moment( end ).format( "LT") );
			    $( "#dialog" ).dialog( "open" );
  
			},
			//Triggered when dragging stops and the event has moved to a different day/time.
			eventDrop: function(event, delta) {
			    //alert("Drop! " + event);
                var start = moment(event.start).format( "YYYY-MM-DD HH:mm:ss");
                var end   = moment(event.end).format( "YYYY-MM-DD HH:mm:ss");
                $.ajax({
                    url: 'jqhelp/calendar.php',
                    data: {
                        task:  'updateTimestamp', 
                        start:  start,
                        end:    end,
                        id:     event.id ? event.id : $( "#id" ).val()
                        },
                    type: "POST",
                    success: function(json) {
                         //alert('Event verschoben');
                    },
                    error: function () {
                        alert('Ajax Error');
                    }
                });
            },
            //Triggered when resizing stops and the event has changed in duration. Dauer
            eventResize: function(event) {
                var start = moment(event.start).format( "YYYY-MM-DD HH:mm:ss");
                var end   = moment(event.end).format( "YYYY-MM-DD HH:mm:ss");
                $.ajax({
                    url: 'jqhelp/calendar.php',
                    data: {
                        task:  'updateTimestamp', 
                        start: start,
                        end: end,
                        id: event.id
                    },
                    type: "POST",
                    success: function(json) {
                        //alert('Zeit geändert');
                    },
                    error: function () {
                        alert('Ajax Error');
                    }
                });
            },
			
			events: 'jqhelp/calendar.php',
			data: { task:  'getEvents' },
			type: "POST",    
			
		});
		$("select").selectBoxIt({
            theme:       "jqueryui",
            autoWidth:   true,
            height: "12"
            //hideCurrent:  true,
            
        })
		$( "div#radioTermin,div#radioPrio" ).buttonset();//.find('label').height(28);;
		$(".inp-checkbox").button({ text: false})
            .click(function(e) {
                $(this).button("option", {
                    icons: {
                        primary: $(this)[0].checked ? "ui-icon-check" : ""
                    }
                });
           
            });

	});

</script>
<style>

	body {
		margin: 0;
		padding: 0;
		font-family: "Lucida Grande",Helvetica,Arial,Verdana,sans-serif;
		font-size: 14px;
	}

	#calendar {
		/*width: 98%;*/
		margin: 40px auto;
	}


    #titleDesig     { position:absolute; top:20px; left:32px; }
    #titleInp       { position:absolute; top:20px; left:95px;}
    #radioTermin    { position:absolute; top:10px; left:465px;}
    #start          { position:absolute; top:50px; left:32px; }
    #startDateInp   { position:absolute; top:50px; left:95px;}
    #startTimeInp   { position:absolute; top:50px; left:195px; }
    #chkboxAllDay   { position:absolute; top:45px; left:295px; }
    #end            { position:absolute; top:80px; left:32px; }
    #endDateInp     { position:absolute; top:80px; left:95px; }
    #endTimeInp     { position:absolute; top:80px; left:195px;}
    #kategorie      { position:absolute; top:120px; left:34px; }
    #kategorieDrop  { position:absolute; top:140px; left:32px;}
    #user           { position:absolute; top:120px; left:220px; }
    #userDrop       { position:absolute; top:140px; left:218px;}
    #prio           { position:absolute; top:120px; left:400px; }
    #radioPrio      { position:absolute; top:140px; left:398px;}
    #descTitle      { position:absolute; top:180px; left:30px;}
    #desc           { position:absolute; top:180px; left:30px;}
    .title{
         width: 350px;
    }    
    .date{
         width: 90px;
    }
    .time{
         width: 80px;
    }
    .test{
         width: 60px;
    } 
    .inp-checkbox+label {
        margin: .5em;
        width:16px; 
        height:16px; 
        vertical-align:middle;
    }
    .selectboxit-container .selectboxit-options {width: 125px;}      
    .selectboxit-container span, .selectboxit-container .selectboxit-options a {height: 25px; line-height: 25px;}
    .radio+label{ 
       /* height: 25px;/*ToDo Buttonhöhe verringern*/
    }​

        
</style>


</head>
<body>
<?php 
    echo $menu['pre_content'];
    echo $menu['start_content'];
    echo '<div class="ui-widget-content">';
?>

    <div id="dialog" class="event-dialog" title="Event">
        <div id="dialog-inner">
            <div id="titleDesig">
              <b>Title: </b> 
            </div> 
               
            <div id="titleInp">
                <input type="text"  id="title" class=" ui-widget-content ui-corner-all title">
                <input type="text"  name="id" id="id"  style="visibility: hidden" class="ui-widget-content ui-corner-all test">
            </div>
            <div id="radioTermin">
                <form>
                    <input type="radio" id="termin" class="radio" name="radioTermin" checked="checked" value='0' ><label for="termin"    >Termin </label>
                    <input type="radio" id="assignment" class="radio" name="radioTermin" value='1' ><label for="assignment">Aufgabe</label>
                </form>
            </div>            
            <div id="start">
              <b>Start: </b> 
            </div>    
            <div id="startDateInp">
                <input type="text"  name="date-start" id="startDate" class="text ui-widget-content ui-corner-all date">
            </div>
            <div id="chkboxAllDay"><input class="inp-checkbox" id="allDay" value='t' type="checkbox"><label for="allDay"></label> ganztags </div> 
            <div id="startTimeInp">
                <input type="text"  name="date-start" id="startTime" class="text ui-widget-content ui-corner-all time">
            </div>
            <div id="end">
              <b>Ende: </b> 
            </div>    
            <div id="endDateInp">
                <input type="text"  name="date-start" id="endDate" class="text ui-widget-content ui-corner-all date">
            </div>
            <div id="endTimeInp">
                <input type="text"  name="date-start" id="endTime" class="text ui-widget-content ui-corner-all time">
            </div>
            <div id="kategorie">
                Kategorie:
            </div> 
            <div id="kategorieDrop">
                <select class="b1" name="kdviewre">
                    <option value="1" checked >beruflich
                    <option value="2" >privat
                    <option value="3" >Geburtstag
                    <option value="4" >Sontige
                </select> 
            </div>
            <div id="user">
                Benutzer:
            </div> 
            <div id="userDrop">
                <select class="b1" name="user">
                    <option value="1" checked >Ronny kumke
                    <option value="2" >Dennis Sonnwald
                    <option value="3" >Martin Gröni
                    <option value="4" >Maria Carry
                </select> 
            </div>
            <div id="prio">
                Priorität:
            </div>
            <div id="radioPrio">
                <form>
                    <input type="radio" id="prioLow"  name="radioPrio" value='0' ><label for="prioLow">gering</label>
                    <input type="radio" id="prioNorm" name="radioPrio" checked="checked" value='1' ><label for="prioNorm">normal</label>
                    <input type="radio" id="prioHigh" name="radioPrio" value='1' ><label for="prioHigh">hoch</label>
                </form>                
            </div>           
                       

            <textarea name="desc" id="desc" class="text ui-widget-content ui-corner-all" rows="10" cols="64"></textarea>
        </div>               

        
    </div>    
    
    <div id='calendar'></div>
<?php 
    $menu['end_content'];
    echo "</div>"
?>
</body>
</html>
