<!DOCTYPE html>
<html>
<head>
<meta charset='utf-8' />

<?php
    require_once( __DIR__.'/inc/stdLib.php' );
    $menu = $_SESSION['menu'];
    echo $menu['stylesheets'];
    echo $menu['javascripts'];
    echo $head['THEME'];
    echo $head['T8'];
?>

<script>
  $( document ).ready( function(){
    const data = [
      { "name": "externDatabase","label": "Extern Database", "type": "headline" },
      { "name": "GEODB", "label": "Geo Database:", "type": "checkbox", "tooltip": "depracted" },
      { "name": "BLZDB", "label": "BLZ Database:", "type": "checkbox", "tooltip": "depracted"},
      { "name": "contacthread", "label": "Contac thread", "type": "headline" },
      { "name": "CallEdit", "label": "Call edit:", "type": "checkbox", "tooltip": "Tooltip" },
      { "name": "email", "label": "Email", "type": "headline" },
      { "name": "MailFlag", "label": "Mail Flag:", "type": "select", "data":["flagged", "Answered", "Seen", "Deleted", "Draft"], "tooltip":"depracted"},
      { "name": "Expunge", "label": "Expunge:", "type": "checkbox", "tooltip": "Tooltip" },
      { "name": "logmail", "label": "Log mail:", "type": "checkbox", "tooltip": "Tooltip" },
      { "name": "Maps", "label": "Maps", "type": "headline" },
      { "name": "streetview_man", "label": "Streetview:", "type": "input", "size": "100", "tooltip": "Tooltip" },
      { "name": "planspace_man", "label": "Planspace:", "type": "input", "size": "1", "tooltip": "Tooltip" },
      { "name": "user-friendly links", "label": "User-friendly links", "type": "headline" },
      { "name": "dir_group", "label": "Group:", "type": "input", "size": "1", "tooltip": "Tooltip" },
      { "name": "dir_mode", "label": "Mode:", "type": "input", "size": "1", "tooltip": "Tooltip" },
      { "name": "misc", "label": "Misc", "type": "headline" },
      { "name": "listLimit", "label": "Listlimit:", "type": "input", "size": "1", "tooltip":"Maximum number of displayed items in a list" },
      { "name": "contex for telefonintegration", "label": "Contex for telefonintegration", "type": "headline" },
      { "name": "external_contex", "label": "External Contex:", "type": "input", "size": "60", "tooltip": "External Contex, seperated by semicolon" },
      { "name": "internal_fon", "label": "Internal Fon:", "type": "input", "size": "60", "tooltip": "Internal Phones, seperated by semicolon" }
    ];

    var tabledata = '';
    $.each( data, function( i, item ){
      if( item.type == 'headline' ) tabledata += '<tr><td colspan="2"><b>' + kivi.t8( item.label ) + '</b></td></tr>';
      if( item.type == 'checkbox' ) tabledata += '<tr><td>' + kivi.t8( item.label ) + '</td><td><input type="checkbox" id="' + item.name + '" name="'+ item.name + '" value="true" title="' + kivi.t8( item.tooltip ) + '"></input></td></tr>';
      if( item.type == 'input' )    tabledata += '<tr><td>' + kivi.t8( item.label ) + '</td><td><input type="text" id="' + item.name + '" name="'+ item.name + '" size="' + item.size + '" title="' + kivi.t8( item.tooltip ) + '"></input></td></tr>';
      if( item.type == 'select' ){
        tabledata += '<tr><td>' + kivi.t8( item.label ) + '</td><td><select type="select" id="' + item.name + '" name="'+ item.name + '" title="' + kivi.t8( item.tooltip ) + '">';
        $.each( item.data, function( i, item ){ tabledata += '<option value="' + item + '">' + kivi.t8( item ) + '</option>'; } );
        tabledata += '</select></input></td></tr>';
      }
    })

    $( "#sitetable > tbody" ).append( tabledata );

    $.ajax({
      url: 'ajax/defaults.php',
      type: 'POST',
      data: { action: 'getDefaults' },
      success: function ( data ){
        $.each( data, function( i, item ){
          if( $( '#' + item.key ).attr('type') == 'checkbox' ) $( '#' + item.key ).prop('checked', item.val == 'true' || item.val == 't' ? true : false  );
          if( $( '#' + item.key ).attr('type') == 'text' )   $( '#' + item.key ).val( item.val );
          if( $( '#' + item.key ).attr('type') == 'select' ) $( '#' + item.key + ' option[value=' + item.val + ']').attr( 'selected', true );
        })
      },
      error: function () {
        alert( 'Error: getDefaults()!' )
      }
    });//ajax

    $( '#head' ).text( kivi.t8( 'Default Configuration' ) );

    $( "#save" ).button({
      label: kivi.t8( 'save' )
    }).css({
      'margin':'5px'
    }).click( function(){
      var formdata = $( "#sitetable input,select" ).serializeArray();
      $( '#sitetable input[type="checkbox"]:not(:checked)' ).each( function( i, e ){
        formdata.push( { name: e.getAttribute( "name" ), value: false } ); //put unchecked boxes in array
      });
      const newArrayFormdata = formdata.map( ( { name: key, value: val, ...rest } ) => ( { key, val, ...rest } ) ); //name -> key, value -> val (colunmname in database)
      $.ajax({
        url: 'ajax/defaults.php',
        type: 'POST',
        data: { action: 'saveDefaults', data: newArrayFormdata },
        success: function ( data ) {
            //if( data ) alert( );
        },
        error: function () {
            alert( 'Error: saveDefaults()!' );
        }
    });
  });//save button

  $( document ).tooltip();
});

</script>
</head>

<body>
<?php
    echo $menu['pre_content'];
    echo $menu['start_content'];
?>

  <p id="head" class="ui-state-highlight ui-corner-all tools" style="margin-top: 20px; padding: 0.6em;"></p>
  <table id="sitetable">
    <thead></thead>
    <tbody></tbody>

  </table>

  <button id="save"></button>


<?php echo $menu['end_content']; ?>

</html>
