<!DOCTYPE html>
<html>
<head>
<meta charset='utf-8' />

<?php
    require_once __DIR__.'/inc/stdLib.php';
    $menu = $_SESSION['menu'];
    echo $menu['stylesheets'];
    echo $menu['javascripts'];
    echo $head['JQTABLE'];
    echo $head['THEME'];
    echo $head['T8'];
?>


<script>
  $( document ).ready( function(){
    $.ajax({
      url: 'ajax/ecTerminalData.php',
      type: "POST",
      data: { 'action': 'getTerminalData' },
      success: function( res ){
        var ip = res[0].val;
        var port = res[1].val;
        var passwd = res[2].val;

        $( '#end_of_day' ).button({
          label: kivi.t8( 'End of day' )
        }).css({
          'margin':'5px'
        }).click( function(){
          $.ajax({
            url: 'ajax/ecTerminal.py',
            type: "POST",
            timeout: 100,
            data: { 'action':'end_of_day', 'ip': ip,'port': port, 'passwd': passwd }
          });
        });

        $( '#payment' ).button({
          label: kivi.t8( 'Pay' )
        }).css({
          'margin':'5px'
        }).click( function(){
          $.ajax({
            url: 'ajax/ecTerminal.py',
            type: "post",
            timeout: 100,
            data: { 'action':'pay', 'ip': ip,'port': port, 'passwd': passwd, 'amount': $( '#amount' ).val(), 'name': '' }
          });
        });

      },
      error: function(){
        alert( 'Error: getTerminalData() ');
      }
    })

    $( '#amount' ).focus().keyup( function(e){
      if( /\D/g.test( this.value ) ) this.value = this.value.replace( /\D/g, '' ); //digits only
    });
    $( '#headline' ).html( 'EC Terminal' ).css( 'font-weight', 'bold' );
    $( '#amountlable' ).html( kivi.t8( 'Amount without comma') +': ' ).css( 'font-weight', 'bold' );

  });

</script>

</head>

<body>
<?php
    echo $menu['pre_content'];
    echo $menu['start_content'];
?>

  <p id="headline" class="ui-state-highlight ui-corner-all tools" style="margin-top: 20px; padding: 0.6em;"></p>
  <table style="margin-left:10px;">
    <tr><td id="amountlable"></td></td><td><input type="text" size="7" id="amount"></input></td><td><button id="payment"></button></td></tr>
    <tr><td><button id="end_of_day"></button></td><td></td><td></td></tr>
  </table>


<?php echo $menu['end_content']; ?>

</html>