<!DOCTYPE html>
<html>
<head>
<meta charset='utf-8' />
<?php
    require_once("inc/stdLib.php");
    $menu = $_SESSION['menu'];
    $head = mkHeader();
    echo $menu['stylesheets'];
    echo $head['FULLCALCSS'];
    echo $head['BOXCSS'];
    echo $head['COLORPICKERCSS'];
    echo $head['JQUERY'];   
    echo $head['JQUERYUI'];
    echo $head['THEME'];
    echo $head['FULLCALJS'];
    echo $head['JQBOX'];
    echo $head['COLORPICKERJS'];
    //print_r( $_SESSION );
    /*****************************************************************************************************************************
    Grundsätze: Content wird via Ajax im Json-Format geholt und an die entsprechenden Container verteilt
                Daten werden ohne Reload einfach via Ajax gespeichtert.
                Fürs Holen und Schreiben von Daten befindet sich unter jqhelp eine gleichnamige Datei mit der Extension ".php"
                Auf das Benutzen der Variable $_SESSION sollte weitestgehend verzichtet werden.  
                Statt JS einzusetzen sollte auf die jQuery-Methoden zurückgegriffen werden.        
    ******************************************************************************************************************************/

?>
<script>

    $(document).ready(function() {
        $( "#example" ).html( "Hello World" ).css({
            fontSize: "36px",
            fontWeight: "bold",
            color: "red",
        }).delay( 1000 ).fadeOut( 6000 ).delay( 1000 ).fadeIn( 10000 );
    });
</script>
<style>
    #example    { position:absolute; top:130px; left:87px; }
</style>
</head>
<body>
<?php 
    echo $menu['pre_content'];
    echo $menu['start_content'];
?>
<div class="ui-widget-content" style="height:600px">
<div id="example"></div>
<!--
Hier stehen die vielen Div-Container    
-->  
            




</div>
<?php $menu['end_content']; ?>
</body>
</html>