<!DOCTYPE html>
<html>
<head>
<meta charset='utf-8' />

<?php
    require_once("inc/stdLib.php");
    $menu = $_SESSION['menu'];
    echo $menu['stylesheets'];
    echo $menu['javascripts'];
    //echo $head['JQUERY'];
    //echo $head['JQUERYUI'];
    echo $head['JQTABLE'];
    echo $head['THEME'];
    echo $head['JUI-DROPDOWN'];

    /*****************************************************************************************************************************
    Grundsätze: Content wird via Ajax im Json-Format geholt und an die entsprechenden Container verteilt
                Daten werden ohne Reload einfach via Ajax gespeichert.
                Fürs Holen und Schreiben von Daten befindet sich unter jqhelp eine gleichnamige Datei mit der Extension ".php"
                Auf das Benutzen der Variable $_SESSION sollte weitestgehend verzichtet werden.
                Statt JS einzusetzen sollte auf die jQuery-Methoden zurückgegriffen werden.
                Url-Parameter können mit $.urlParam( 'ParameterName' ) gelesen werden.
    ******************************************************************************************************************************/

?>

<script>


$(document).ready(function() {

    $("#senddialog").dialog({
        autoOpen: false,
        width:400,
        height:250,
        minWidth:300,
        minHeight:200,
        maxWidth:800,
        maxHeight:800,
        buttons: [{
            text: 'Save', //translate
            click: function() {
//                //Datumsstring mit aktuellem Datum / aktueller Uhrzeit bauen
//                // einzelne Daten holen
//                var date = new Date();
//                var year = date.getFullYear();
//                var month = date.getMonth();
//                var day = date.getDate();
//                var hour = date.getHours();
//                var minute = date.getMinutes();
//                var second = date.getSeconds();
//
//                // Monate gehen von 0 bis 11, darum:
//                month += 1;
//
//                // bei Werten unter 10 "0" voranstellen
//                if (month < 10) month = "0" + month;
//                if (day < 10) day = "0" + day;
//                if (hour < 10) hour = "0" + hour;
//                if (minute < 10) minute = "0" + minute;
//                if (second < 10) second = "0" + second;
//
//                // Datumsstring zusammenbauen
//                var datum = year + "/" + month + "/" + day + " " + hour + ":" + minute + ":" + second;
//                $("#datetime").val(datum);

                var object = {};
                // Formular-inputs in ein array
                var array = $('#fsend').serializeArray();
                // Ein object aus dem array machen
                $.each(array, function(index, item) {
                    object[item.name] = item.value;
                });
                //mit ajax als JSON verschicken
                $.ajax({
                    data: { action: "newEntry", data: JSON.stringify(object)},
                    dataType: 'json',
                    type: 'POST',
                    url: "ajax/example.php",
                    success: function(){
                        alert("Gesendet");
                    },
                    error:  function(){
                        alert("Senden der Daten fehlgeschlagen!");
                    }
                })
            }
        }, //Ende Button "Save"
        {
            text: 'Get',//translate
            click: function(){
                $.ajax({
                    dataType: 'json',
                    url: 'ajax/example.php?action=getData',
                    method: "GET",
                    success: function( json ) {
                        //var obj = json;
                        var obj = JSON.parse(json);

                        $("#gdtable").html('<table border="1">' +
                                           '<tr> <th>ID</th> <th>Date of Birth</th> <th>Name</th> <th>Age</th> <th>Comments</th> </tr>' +
                                           '<tr> <td>' + obj.id + '</td> <td>' + obj.date_time + '</> <td>'+ obj.c_name + '</td>' +
                                           '<td>' + obj.c_age + '</td> <td>' + obj.c_comments + '</td> </tr>' +
                                           '</table>');
                    },
                    error:  function(){
                        alert("Holen der Daten fehlgeschlagen!");
                    }
                })
            }
        }] //Ende buttons[]
    }); //Ende senddialog()

    $( function() {
        $( "#datetime" ).datepicker();
    });

    $( "#newbtn" ).button().html("New").click(function() {
      $("#senddialog").dialog("open");
    });


}); //Ende $(document).ready()





</script>
<style>
.ui-menu { width: 180px; }

/*#read{   position:absolute; top:120px; left:225px; width: 80%; background-color:#dfd; border:1px solid #888; }
#results{   position:absolute; top:40px; left:235px; width: 80%;  }

.contex_sub_menu, .contex_main_menu {
    display: none;
    z-index: 1000;
    position: absolute;
    overflow: hidden;
    border: 1px solid #CCC;
    white-space: nowrap;
    font-family: sans-serif;
    background: #FFF;
    color: #333;
    border-radius: 5px;
    padding: 0;
}

// Each of the items in the list
.contex_sub_menu li, .contex_main_menu li {
    padding: 8px 12px;
    cursor: pointer;
    list-style-type: none;
    transition: all .3s ease;
}

.contex_sub_menu li:hover, .contex_main_menu li:hover {
    background-color: #DEF;
}
*/
table.tablesorter { width:auto; cursor:pointer; }



</style>
</head>

<body>
<?php
    echo $menu['pre_content'];
    echo $menu['start_content'];
?>

<?php echo $menu['end_content']; ?>

 <p class="ui-state-highlight ui-corner-all tools" style="margin-top: 20px; padding: 0.6em;">Testfile</p>
 <div id="example" style="position:absolute"></div>



 <div id="senddialog" title="Daten an Server schicken und vom Server holen">
  <p>
   <form id="fsend">
    <table>
     <tr>
      <td><label>Date of Birth</label></td>
      <td><input type="text" name="datetime" id="datetime"></td>
     </tr>
     <tr>
      <td><label>Name</label></td>
      <td><input type="text" name="name" id="name"></td>
     </tr>
     <tr>
      <td><label>Age</label></td>
      <td><input type="text" name="age" id="age"></td>
     </tr>
     <tr>
      <td><label>Comments</label></td>
      <td><input type="text" name="comments" id="comments"></td>
     </tr>
    </table>
   </form>
  </p>
 </div>

 <div id="gdtable">Daten vom Server anzeigen</div>
 <div id="newbtn"></div>



</body>
</html>
