<!DOCTYPE html>
<html>
<head>
<meta charset='utf-8' />

<?php
    require_once("inc/stdLib.php");
    $menu = $_SESSION['menu'];
    echo $menu['stylesheets'];
    echo $menu['javascripts'];
    echo $head['JQUERY'];
    echo $head['JQUERYUI'];
    echo $head['JQTABLE'];
    echo $head['THEME'];
    echo $head['JUI-DROPDOWN'];

    /*****************************************************************************************************************************
    Grundsätze: Content wird via Ajax im Json-Format geholt und an die entsprechenden Container verteilt
                Daten werden ohne Reload einfach via Ajax gespeichert.
                Fürs Holen und Schreiben von Daten befindet sich unter jqhelp eine gleichnamige Datei mit der Extension ".php"
                Auf das Benutzen der Variable $_SESSION sollte weitestgehend verzichtet werden.
                Statt JS einzusetzen sollte auf die jQuery-Methoden zurückgegriffen werden.
                Url-Parameter können mit $.urlParam( 'ParameterName' ) gelesen werden.
    ******************************************************************************************************************************/

?>

<script type="text/javascript" src="lxcars/jQueryAddOns/date-time-picker.js"></script>
<script type="text/javascript" src="lxcars/jQueryAddOns/german-date-time-picker.js"></script>


<script>


$(document).ready(function() {
    $("#senddialog").dialog({
        width:'auto',
//      width: 400,
//        height:250,
//        minWidth:300,
//        minHeight:200,
//        maxWidth:800,
//        maxHeight:800,
        buttons: [{
            text: 'Save', //translate
            click: function() {

                var object = {};
                // Formular-inputs in ein array
                var array = $('#fsend').serializeArray();
                // Ein object aus dem array machen
                $.each(array, function(index, item) {
                    object[item.name] = item.value;
                });
                //mit ajax als JSON verschicken
                $.ajax({
                    data: { action: "newEntry", data: JSON.stringify(object)},
                    dataType: 'json',
                    type: 'POST',
                    url: "ajax/example.php",
                    success: function(){
                        alert("Gesendet");
                    },
                    error:  function(){
                        alert("Senden der Daten fehlgeschlagen!");
                    }
                })
            }
        }, //Ende Button "Save"
        {  text: 'Get',//translate
            click: function(){
                $.ajax({
                    dataType: 'json',
                    url: 'ajax/example.php?action=getData',
                    method: "GET",
                    success: function( json ) {
                        var obj = JSON.parse(json);
                        $("#getdialog").dialog({
                            width:500,
                            height:200
                        }).dialog("open").html( '<table border="1">' +
                            '<tr> <th>ID</th><th>Name</th><th>Alter</th><th>Bemerkungen</th><th>Datum</th></tr>' +
                            '<tr> <td>' + obj.id + '</td> <td>' + obj.c_name + '</td> <td>' + obj.c_age + '</td>' +
                            '<td>' + obj.c_comments + '</td> <td>' + obj.date_time + '</td> </tr> </table> <br>');
                    },
                    error:  function(){
                         alert("Holen der Daten fehlgeschlagen!");
                    }
                })
            }
        }, //Ende Button "Get"
        {
               text: 'Get Last',//translate
            click: function(){
                $.ajax({
                    dataType: 'json',
                    url: 'ajax/example.php?action=getLastData',
                    method: "GET",
                    success: function( json ) {
                        //$("#getdialog").html(json);
                        var obj = JSON.parse(json);
                        $("#getdialog").dialog({
                            width:500,
                            height:200})
                            .dialog("open").html( '<table border="1" class="tablesorter">' +
                                '<tr> <th>ID</th><th>Name</th><th>Alter</th><th>Bemerkungen</th><th>Datum</th></tr>' +
                                '<tr> <td>' + obj.id + '</td> <td>' + obj.c_name + '</td> <td>' + obj.c_age + '</td>' +
                                '<td>' + obj.c_comments + '</td> <td>' + obj.date_time + '</td> </tr> </table>');
                    },
                    error:  function(){
                        alert("Holen der Daten fehlgeschlagen!");
                    }
                })
            }
        }] //Ende buttons[]
    }); //Ende dialog()

    $("#datetime").datetimepicker({
        //dateFormat: 'yy-mm-dd',
        stepMinute: 5,
        hour: 1,
        hourMin: 6,
        hourMax: 19,
        //timeSuffix: ' Uhr',
        timeText: 'Zeit',
        hourText: 'Stunde',
        closeText: 'Fertig',
        currentText: 'Jetzt'
    });

}); //Ende $(document).ready()






</script>
<style>
.ui-menu, #searchfield { width: 180px; }

/*#read{   position:absolute; top:120px; left:225px; width: 80%; background-color:#dfd; border:1px solid #888; }
#results{   position:absolute; top:40px; left:235px; width: 80%;  }

.contex_sub_menu, .contex_main_menu {
    display: none;
    z-index: 1000;
    position: absolute;
    overflow: hidden;
    border: 1px solid #CCC;
    white-space: nowrap;
    font-family: sans-serif;
    background: #FFF;
    color: #333;
    border-radius: 5px;
    padding: 0;
}

// Each of the items in the list
.contex_sub_menu li, .contex_main_menu li {
    padding: 8px 12px;
    cursor: pointer;
    list-style-type: none;
    transition: all .3s ease;
}

.contex_sub_menu li:hover, .contex_main_menu li:hover {
    background-color: #DEF;
}
*/


table.tablesorter { width:auto; cursor:pointer; }


</style>
</head>

<body>
<?php
    echo $menu['pre_content'];
    echo $menu['start_content'];
?>
<!--<div class="ui-widget-content" style="height:700px">
    <ul id="menu"></ul>
    <p>
    <input type="text" id="searchfield"  placeholder="Enter Searchstring">

    </p>
    <div id="read" class="editable"></div>
    <div id="results" style="display:none;">
       <table id="resTable" class="tablesorter">
         <thead>
          <tr>
            <th class="res_id">ID</th>
            <th class="res_category">Category</th>
            <th class="res_version">Version</th>
            <th class="res_content">Row</th>
          </tr>
         </thead>
         <tbody id="tbody">
         </tbody>
       </table>
     </div>
</div>
<ul class='contex_sub_menu'>
  <li data-action="edit">Edit</li>
  <li data-action="delete">Delete </li>
</ul>
<ul class='contex_main_menu'>
  <li data-action="new">New</li>
  <li data-action="edit">Edit</li>
  <li data-action="delete">Delete </li>
</ul>
<div id="newCat">
</div>
<div id="editCat">
</div>
<div id="delCat">
</div>
<div id="delNote">
</div>-->
<?php echo $menu['end_content']; ?>

 <p class="ui-state-highlight ui-corner-all tools" style="margin-top: 20px; padding: 0.6em;">Testfile</p>
<!-- <div id="example" style="position:absolute"></div>
-->


<div id="senddialog" title="Daten an Server schicken und vom Server holen">
  <p>
   <form id="fsend">
    <label>Datum / Uhrzeit</label>
    <input type="text" name="datetime" id="datetime"><br>
    <label>Name</label>
    <input type="text" name="name" id="name"><br>
    <label>Alter</label>
    <input type="text" name="age" id="age"><br>
    <label>Bemerkungen</label>
    <input type="text" name="comments" id="comments">
   </form>
  </p>
</div>



</body>
</html>
