<!DOCTYPE html>
<html>
<head>
<meta charset='utf-8' />
<?php
    require_once("inc/stdLib.php");
    $menu = $_SESSION['menu'];
    $head = mkHeader();
echo $menu['stylesheets'];
echo $menu['javascripts'];
echo $head['CRMCSS'];
echo $head['JQTABLE'];
echo $head['THEME'];
echo $head['JUI-DROPDOWN'];
    /*****************************************************************************************************************************
    Grundsätze: Content wird via Ajax im Json-Format geholt und an die entsprechenden Container verteilt
                Daten werden ohne Reload einfach via Ajax gespeichtert.
                Fürs Holen und Schreiben von Daten befindet sich unter jqhelp eine gleichnamige Datei mit der Extension ".php"
                Auf das Benutzen der Variable $_SESSION sollte weitestgehend verzichtet werden.
                Statt JS einzusetzen sollte auf die jQuery-Methoden zurückgegriffen werden.
                Url-Parameter können mit $.urlParam( 'ParameterName' ) gelesen werden.
    ******************************************************************************************************************************/

?>
<script>



  $(document).ready(function() {
        $( "#dialog" ).dialog({
            width:200,
            height:200,
            minWidth:200,
            minHeight:100,
            maxWidth:400,
            maxHeight:300
        });
        $("#btn1").click(function(){
        alert($("#somename").val());
       });

       $("#btn2").click(function(){
        $("#somename").val().dialog();
       });
    });




</script>

</head>
<body>
<?php
    echo $menu['pre_content'];
    echo $menu['start_content'];
?>

 <p class="ui-state-highlight ui-corner-all tools" style="margin-top: 20px; padding: 0.6em;">.'translate('.:fast search customer/vendor/contacts and contact history:.','firma')'.</p>
<div id="example" style="position:absolute"></div>

<div id="dialog" title="Ein Dialog">
  <p>Dies ist ein Dialog mit minimal 200, maximal 400 Pixeln Breite und minimal 100, maximal 300 Pixeln Höhe.<br>
  Ausgangsgröße ist 200 x 200 Pixel.</p>
</div>

<!--<div id="dialog1" title="Ein Dialog">
  <p>Dies ist ein Test-Dialog</p>
</div>-->
<button id="btn1">Klick!</button><button id="btn2">Auch Klick!</button><br>
 <input id="somename" value="Ein Name">Name</input>

<?php
    echo $menu['end_content'];
    echo $head['TOOLS'];
?>

</body>
</html>
