<!DOCTYPE phtml>
<html>
<head>
<meta charset='utf-8'/>
<?php
    require_once __DIR__.'/inc/stdLib.php';
    $menu = $_SESSION['menu'];
    //$head = mkHeader();//wird nicht mehr benötigt, weil Aufruf in stdlib
    echo $menu['stylesheets'];
    echo $menu['javascripts'];
    echo $head['THEME'];
    echo $head['ELFINDER'];
    echo $head['TRANSLATION'];
?>
<script type="text/javascript">
    $(document).ready(function() {
        var language = kivi.myconfig.countrycode;
        $( ".lang" ).each( function(){
            var key = $( this ).attr( "data-lang" );
            if( $( this ).is( ":input" ) ) $( this ).attr( 'title',  typeof( langData[language][key] ) != 'undefined' ? langData[language][key] : 'LNG ERR'  );
            else $( this ).text( typeof( langData[language][key] ) != 'undefined' ? langData[language][key] : 'LNG ERR'  );
        });
        $.urlParam = function( name ){
            var results = new RegExp( '[\?&]' + name + '=([^&#]*)' ).exec( window.location.href );
            if( results == null ) alert( 'Parameter: "' + name + '" does not exist in "' + window.location.href + '"!' );
            else return decodeURIComponent( results[1] || 0 );
        }

        var cu_type = $.urlParam( 'Q' ) ;
        var cu_number = $.urlParam( 'kdnr' ) ;
        var cu_id = $.urlParam( 'fid' ) ;

        start = function( lng ){
            $('#elfinder').elfinder({
                url : 'jquery-plugins/elFinder/php/connector.minimal.php?Q=' + cu_type + '&number=' + cu_number,
                height : 600,
                defaultView: 'list',
                rememberLastDir : true,
                lang : lng
            });
        }
        if( language != 'en' ){
            $.ajax({
                url : 'jquery-plugins/elFinder/js/i18n/elfinder.' + language + '.js',
                cache : true,
                dataType : 'script'
            }).done( function(){
                start( language );
            }).fail( function(){
                start( 'en' );
            });
        }
        else start( language );


        $('#btn1').button().click(function() {
            window.location.replace("firma1.php?Q=" + cu_type + "&id= " + cu_id);
        });
        $('#btn2').button().click(function() {
            window.location.replace("firma2.php?Q=" + cu_type + "&fid=" + cu_id + "&id=" + cu_id);
        });
        $('#btn3').button().click(function() {
            window.location.replace("firma3.php?Q=" + cu_type + "&fid=" + cu_id);
        });
        $('#btn4').button().click(function() {
            window.location.replace("firma4.php?Q=" + cu_type + "&fid=" + cu_id);
        });
    });
</script>
<style>
</style>
</head>

<body>
<?php
    echo $menu['pre_content'];
    echo $menu['start_content'];
?>
<div class="ui-widget-content" style="height:700px">
<p class="ui-state-highlight ui-corner-all tools" style="margin-top: 20px; padding: 0.6em;"><b>Detailansicht Kunde</b></p>

<div id='menubox'>
    <button id="btn1"><label data-lang='CUSTOMBASE' class='lang' ></label></button>
    <button id="btn2"><label data-lang='CONTACTS' class='lang' ></label></button>
    <button id="btn3"><label data-lang='SALES' class='lang' ></label></button>
    <button id="btn4"><label data-lang='DOCUMENTS' class='lang' ></label></button>
</div>
<br>
<div id="elfinder"></div>

</div>
<?php echo $menu['end_content']; ?>
<?php echo $head['TOOLS']; ?>
</body>
</html>