<!DOCTYPE html>
<html>
<head>
<meta charset='utf-8' />

<?php
    require_once("inc/stdLib.php");
    $menu = $_SESSION['menu'];
    $head = mkHeader();
    echo $menu['stylesheets'];
    //echo $head['FULLCALCSS'];
    //echo $head['BOXCSS'];
    //echo $head['COLORPICKERCSS'];
    echo $head['JQUERY'];   
    echo $head['JQUERYUI'];
    echo $head['THEME'];
    echo $head['TINYMCE'];
    //echo $head['JQBOX'];
    //echo $head['COLORPICKERJS'];
    //print_r( $_SESSION );


?>

<script>

    $(document).ready(function(){
        tinymce.init({
            selector: "#content",
        });

         
        $.ajax({
            url: 'jqhelp/knowledge.php',
            data: { task:  'getCategories'  },
            type: "POST",
            success: function( json ) {
                var obj = JSON.parse( json.trim() );
                //console.log( JSON.stringify( obj ) );
                $.each( obj[0].maingroup, function( i, val ){

                    $( "#menu" ).append("<li id='main_" + val.id + "'>" + val.labeltext + "</li>"  );
     
                });
                $.each( obj[1].undergroup, function( i, val ){
                    if( !$('#main_'  + val.maingroup + ' ul').length > 0 ){
                        $( '#main_' + val.maingroup ).append( "<ul id='ul" + val.maingroup + "'></ul>" );
                    }   
                    $( "#ul" + val.maingroup  ).append("<li id='msub_" + val.id + "'>" + val.labeltext + "</li>" );
     
                });
                $( '#menu' ).menu(); 
                $( '[id^=main_]' ).on( 'click', function(event) {
                    console.log( event.target.id.substring( 5 ) );                    
                    //alert(event.target.id.substring( 5 ))
                    $.ajax({
                        url: 'jqhelp/knowledge.php',
                        data: { task:  'getArticle' , category: event.target.id.substring( 5 ) }, 
                        type: "POST",
                        success: function( json ) {
                            var obj = JSON.parse( json.trim() );
                            //alert(JSON.stringify( obj[0].content )  );
                            //console.log( JSON.stringify( obj ) );
                            $( '#content' ).html( obj[0].content );
                            $( "#menu" ).refresh();
                       }
                    })
                });

 
                
            },
            error: function () {
                alert('Ajax Error');
            }
        });
           
        


        
        
    });

</script>
<style>

.ui-menu { width: 220px; }
</style>    

</head>
<body>
<?php 
    echo $menu['pre_content'];
    echo $menu['start_content'];
?>
<div class="ui-widget-content" style="height:600px">

<ul id="menu"></ul>        


    <div class="ui-widget-content" style="height:600px" id='content'></div>

   




</div>
<?php $menu['end_content']; ?>
</body>
</html>