<!DOCTYPE html>
<html>
<head>
<meta charset='utf-8' />

<?php
    require_once("inc/stdLib.php");
    $menu = $_SESSION['menu'];
    $head = mkHeader();
    echo $menu['stylesheets'];
    echo $menu['javascripts'];
    //echo $head['FULLCALCSS'];
    //echo $head['BOXCSS'];
    //echo $head['COLORPICKERCSS'];
    echo $head['JQUERY'];
    echo $head['JQUERYUI'];
    echo $head['THEME'];
    echo $head['TINYMCE'];
    //echo $head['JQBOX'];
    //echo $head['COLORPICKERJS'];
    //print_r( $_SESSION );


?>

<script>

$(document).ready(function(){


tinymce.init({
    selector: 'div.editable',
    inline: true,
    plugins: [
        'advlist autolink lists link image charmap print preview anchor',
        'searchreplace visualblocks code fullscreen',
        'insertdatetime media table contextmenu paste'
    ],
    toolbar: 'mybutton | undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image | table',
    setup: function(editor) {
    editor.addButton('mybutton', {
      type: 'menubutton',
      text: 'Version',
      icon: false,
      menu: [{
        text: 'save',
        onclick: function() {
          editor.insertContent('saved ');
        }
      }, {
        text: 'next/new',
        onclick: function() {
          editor.insertContent('&nbsp;<em>Menu item 2 here!</em>&nbsp;');
        }
      },
       {
        text: 'previous',
        onclick: function() {
          editor.insertContent('Previous Version was loaded');
        }
      }]
    });
  },

});

      var category_id;

      $.ajax({
            dataType: "json",
            url: "ajax/knowledge.php?action=getCategories",
            method: "GET",
            success: function( json ) {
               var obj = JSON.parse( json.trim() );
                //console.log( JSON.stringify( obj ) );
                $.each( obj[0].maingroup, function( i, val ){

                    $( "#menu" ).append("<li id='main_" + val.id + "'>" + val.labeltext + "</li>"  );

                });
                $.each( obj[1].undergroup, function( i, val ){
                    if( !$('#main_'  + val.maingroup + ' ul').length > 0 ){
                        $( '#main_' + val.maingroup ).append( "<ul id='ul" + val.maingroup + "'></ul>" );
                    }
                    $( "#ul" + val.maingroup  ).append("<li id='msub_" + val.id + "'>" + val.labeltext + "</li>" );

                });
                $( '#menu' ).menu();
                $( '[id^=main_]' ).on( 'click', function(event) {
                    //console.log( event.target.id.substring( 5 ) );
                    //alert(event.target.id.substring( 5 ))
                    category_id = event.target.id.substring( 5 );
                    $.ajax({
                        dataType: "json",
                        url: "ajax/knowledge.php?action=getArticle&data=" + category_id,
                        method: "GET",
                        success: function( json ) {
                            var obj = JSON.parse( json.trim() );
                            //alert(JSON.stringify( obj[0].content )  );
                            //console.log( JSON.stringify( obj ) );
                            $('#read').html(obj[0].content);

                        }
                    })
                });

                $( '[id^=main_]' ).bind("contextmenu", function (event) {
                    //Avoid the real one
                    event.preventDefault();

                    // Show contextmenu
                   // alert(event.target.id.substring( 0, 4 ));
               if ( event.target.id.substring( 0, 4 ) == "main" ) {                
                   $(".contex_main_menu").finish().toggle(100).

                    // In the right position (the mouse)
                    css({
                        top: event.pageY + "px",
                        left: event.pageX + "px"
                    }); 
                }
                else{                
                   $(".contex_sub_menu").finish().toggle(100).

                    // In the right position (the mouse)
                    css({
                        top: event.pageY + "px",
                        left: event.pageX + "px"
                    }); 
                }
                }).bind("mousedown", function (event) {
                category_id = event.target.id.substring( 5 );
                // If the clicked element is not the menu
                    if (!$(event.target).parents(".contex_main_menu").length > 0) {
                        // Hide it
                        $(".contex_main_menu, .contex_sub_menu").hide(100);
                    }
                    if (!$(event.target).parents(".contex_sub_menu").length > 0) {
                        // Hide it
                        $(".contex_main_menu, .contex_sub_menu").hide(100);
                    }
                });
            },
            error: function () {
                alert('Ajax Error');
            }
    });

    // If the menu element is clicked
    $(".contex_sub_menu li").click(function(event){
        // This is the triggered action name
        switch($(this).attr("data-action")) {
            // A case for each action. Your actions here
            case "edit":  alert('Category: ' + category_id + ' wird editiert' ) ; break;
            case "delete": alert('Category: ' + category_id + ' wird gelöscht'); break;

        }
        // Hide it AFTER the action was triggered
        $(".contex_sub_menu").hide(100);
    });
    // If the menu element is clicked
    $(".contex_main_menu li").click(function(event){
        // This is the triggered action name
        switch($(this).attr("data-action")) {
            // A case for each action. Your actions here
            case "new": alert('Category: ' + category_id + ' neue Kategorie wird erzeugt'); break;
            case "edit":  alert('Category: ' + category_id + ' wird editiert' ) ; break;
            case "delete": alert('Category: ' + category_id + ' wird gelöscht'); break;
            

        }
        // Hide it AFTER the action was triggered
        $(".contex_main_menu").hide(100);
    });

    $("#last").button({label:"last"}).click(function (event) {
           $.ajax({
              dataType: "json",
              url: "ajax/knowledge.php?action=getLastArticle&data=" + category_id,
              method: "GET",
              success: function( json ) {
                    var obj = JSON.parse( json.trim() );
                    $('#read').html(obj[0].content);

             }
        })
    });

    $("#save").button({label:"save"}).click(function (event) {
        var artContent = $("#read").html();
        alert(artContent);
        $.ajax( {
            url: 'ajax/knowledge.php',
            data: {action: "updateContent",  data: { content : artContent,  cat_id: category_id } },
            dataType: 'json',
            type: 'post',
            success: function(json) {
                //alert(JSON.stringify(json));
            },
            error: function () {
                alert('Ajax Error');
           }
        });
    });

    $("#nextvers").button({label:"nextversion"}).click(function (event) {
        var artContent = $("#read").html();
        $.ajax({
           url: 'ajax/knowledge.php',
           data: {action: "nextVersion",  data: { content : artContent,  cat_id: category_id } },
           dataType: 'json',
           type: 'post',
           success: function( json ) {
                 //alert(JSON.stringify(json));
           },
           error: function () {
                alert('Ajax Error');
           }

        })
    });

    $("#wortsuche").click(function (event) {
          var searchword = $('#searchfield').val();
          $.ajax({
              dataType: "json",
              url: "ajax/knowledge.php?action=searchArt&data=" + searchword,
              method: "GET",
              success: function( rc ) {
                    alert(JSON.stringify(rc));
                    $('#treffer').append('test');
              }
        })
    });

});

</script>
<style>
.ui-menu { width: 180px; }

#read{   position:absolute; top:120px; left:225px; width: 80%; background-color:#dfd; border:1px solid #888; }
#treffer{   position:absolute; top:55px; left:225px; width: 80%;  }

.contex_sub_menu, .contex_main_menu {
    display: none;
    z-index: 1000;
    position: absolute;
    overflow: hidden;
    border: 1px solid #CCC;
    white-space: nowrap;
    font-family: sans-serif;
    background: #FFF;
    color: #333;
    border-radius: 5px;
    padding: 0;
}

/* Each of the items in the list */
.contex_sub_menu li, .contex_main_menu li {
    padding: 8px 12px;
    cursor: pointer;
    list-style-type: none;
    transition: all .3s ease;
}

.contex_sub_menu li:hover, .contex_main_menu li:hover {
    background-color: #DEF;
}
</style>

</head>
<body>
<?php
    echo $menu['pre_content'];
    echo $menu['start_content'];
?>
<div class="ui-widget-content" style="height:600px">

    <ul id="menu"></ul>
    <p>
    <input type="text" name="searchfield" id="searchfield" value="">
    <img src="image/search.png" border="0" title=".:search:." align="middle" id='wortsuche'><br>
    </p>
    <p><button id="last"></button></p>
    <p><button id="save"></button></p>
    <p><button id="nextvers"></button></p>
    <div id="read" class="editable"></div>
    <div id="treffer"></div>

</div>
<ul class='contex_sub_menu'>
  <li data-action="edit">Edit</li>
  <li data-action="delete">Delete </li>
</ul>
<ul class='contex_main_menu'>
  <li data-action="new">New</li>
  <li data-action="edit">Edit</li>
  <li data-action="delete">Delete </li>
</ul>
<?php echo $menu['end_content']; ?>
</body>
</html>