<!DOCTYPE html>
<html>
  
<head>
<meta charset='utf-8' />
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
<?php
    require_once __DIR__.'/inc/stdLib.php';
    //echo $head['BOOTSTRAP_CSS'];
    $menu = $_SESSION['menu'];
    echo $menu['stylesheets'];
    echo $menu['javascripts'];
    echo $head['JQTABLE'];
    echo $head['THEME'];
    echo $head['T8'];// Übersetzung mit kivi.t8
    echo $head['BOOTSTRAP_CSS'];
    echo $head['BOOTSTRAP_JS'];

    /*****************************************************************************************************************************
    Grundsätze: Content wird via Ajax im Json-Format geholt und an die entsprechenden Container verteilt
                Daten werden ohne Reload einfach via Ajax gespeichert.
                Fürs Holen und Schreiben von Daten befindet sich unter ajax eine gleichnamige Datei mit der Extension ".php"
                Auf das Benutzen der Variable $_SESSION sollte weitestgehend verzichtet werden.
                Statt JS einzusetzen sollte auf die jQuery-Methoden zurückgegriffen werden.
                Url-Parameter werden als hash gefolgt von einem JSON übergeben.
                Vorteil: Browserhistory funktioniert, F5 funktioniert,
            
               
    ******************************************************************************************************************************/

?>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
<script>
  $( document ).ready( function(){
    $( '#headline' ).html( kivi.t8( 'Headline' ) );
  });

</script>

<style>



</style>
</head>

<body>
<?php
    echo $menu['pre_content'];
    echo $menu['start_content'];
?>



  <p id="headline" class="ui-state-highlight ui-corner-all tools" style="margin-top: 20px; padding: 0.6em;"></p>
  <div id="example" style="position:absolute"></div>
  <div class="container">
    <div  class="row">
        <div  class="col-sm-3">
            <h2>Box  1</h2>
            Anrede :    <select name="gender" id="gender_response">
              <option value=" " disabled selected></option>
              <option value="M">Herr</option>
              <option value="F">Frau</option>
            </select>
        </div>
        <div  class="col-sm-9">
            <h2>Box  2</h2>
            <div class="names">
              <input id="name_txt" type="text" placeholder="Firstname"><br>
              <input type="text" id="zip_code" placeholder="Zip Code">
              <select id="location"> </select>
              <select name="federal_state" id="federal_state" placeholder="Federal State"></select><br>
              <input type="text" id="street" placeholder="street"> 
              <button id="don_e" OnClick="Clicked()">Press me</button>
            </div>

        </div>
        <div></div>
    </div>
</div>


<script type="text/javascript">

  $('#name_txt').keyup(function(e){
    if(e.which == 32){
      $.ajax({
        url: 'ajax/website_r.php',
        type: 'POST',
        // sendet den Namen (#name_txt inhalt) an die website_r.php
        //var txxt = ('#name_txt').val().replace(' ', '')
        data:  { action: 'firstnameToGender', data: { 'name': $('#name_txt').val().replace(' ', '') } },
        // bei Erfolg wird die Funktion ausgerufen welche von der Response der PHP erbt
        success: function( data ){
          // gibt data aus (Response der PHP ) in der console
          console.info( data );      
          // filtert gender aus data und ändert den #response Text zum ausgegeben Geschlecht

          $("#gender_response").val(data["gender"]).change();
        },
        error: function( xhr, status, error ){
          // falls Fehlermeldungen
            console.error("ERROR: ", "Name not found" );
        }
    })
    }
    if(e.which == 13){
      $('#zip_code').focus();
    }
  })
  $( "#name_txt" ).change( function(){
    // sendet eine Post-Anfrage an website_r.php 
     // jquery each, key & value append
  });

  $( '#zip_code' ).keyup( function(){
    $.ajax({
      url: 'ajax/website_r.php',
      type: 'POST',
      data: { action: 'getZipCode', data: { 'zipcode': $('#zip_code').val() } },
      success: function( data ){
        $.each(data, function(index, value){
          var opt = document.createElement('option');
          opt.value = index;
          opt.innerHTML = JSON.stringify( value["ort"]).replace(new RegExp('"', 'g'),'');
          $("#location").append(opt);
        })
        $('#street').focus()
        $('#zip_code').on("input", function(){
          $('#location').empty();
        })
      },
      error: function( xhr, status, error ){
        console.info("ERROR", xhr, status)
      }

    });
    if($('#zip_code').val().length = 5){
      $.ajax({
      url: 'ajax/website_r.php',
      type: 'POST',
      data: {action: 'f_state', data: { 'zipcode': $('#zip_code').val() } },
      success: function( data ){
        $('#federal_state').append($('<option />').text(data['federal_state'])); 
      },
      error: function( xhr, status, error ){
        console.info("ERROR ", xhr, status, error)
      }

    });
    } 
     
    $('#location').change(function(){
      $('#street').focus(); })
  })
  $("#location").on('change', function(){
    $('#street').focus();
  })
  $('#street').on("input", function(){
    $('#street').autocomplete({
      source:function(request, response){
        $.ajax({
          url: 'ajax/website_r.php',
          type: 'POST',
          data: {action: 'street', data:{ 'street': $('#street').val(), 'locality': $('#location option:selected').text() }},
          success: function(data){
            response($.map(data, function(item){
              return{
                value: item.street
              }
            }))
          },
          error: function(xhr, status, error){
            console.error(xhr, error, status)
          },
        });
        autoFocus = true;
      }
    })
    $('#street').on('autocompleteselect', function(){
      $('').focus();
    })
  })
</script>
<?php echo $menu['end_content']; ?>
</html>
