<!DOCTYPE html>
<html>
<head>
<meta charset='utf-8' />

<?php
    require_once __DIR__.'/../inc/stdLib.php';
    $menu = $_SESSION['menu'];
    echo $menu['stylesheets'];
    echo $menu['javascripts'];
    echo $head['JQTABLE'];
    echo $head['THEME'];
    echo $head['T8'];

?>


<script>
  $( document ).ready( function(){
    $.ajax({
      url: '../ajax/ecTerminalData.php',
      type: "POST",
      data: { 'action': 'getTerminalData' },
      success: function( res ){
        //alert( res. );
        console.log( res[0].val );
        var ip = res[0].val;
        var port = res[1].val;
        var passwd = res[2].val;
        
        $( '#end_of_day' ).button({
          label: kivi.t8( 'End of day' )
        }).css({
          'margin':'5px'
        }).click( function(){
          $.ajax({
            url: '../ajax/ecTerminal.py',
            type: "POST",
            timeout: 100,
            data: { 'action':'end_of_day', 'ip': ip,'port': port, 'passwd': passwd },
              //success: function( res ){
                //alert( res.data );
              //}
          });
        });
    
        $( '#payment' ).button({
          label: kivi.t8( 'Payment' )
        }).css({
          'margin':'5px'
        }).click( function(){
          $.ajax({
            url: '../ajax/ecTerminal.py',
            type: "post",
            timeout: 100,
            data: { 'action':'pay', 'ip': ip,'port': port, 'passwd': passwd, 'amount': $( '#amount' ).val(), 'customer':'Herr Ronny Zimmermann' }
          });
        });
    
      },
      error: function(xhr, status, error) {
        var err = eval("(" + xhr.responseText + ")");
        alert(err.Message);
      }
    })
    //alert( ip );

    


});

</script>

</head>

<body>
<?php
    echo $menu['pre_content'];
    echo $menu['start_content'];
?>

  <p class="ui-state-highlight ui-corner-all tools" style="margin-top: 20px; padding: 0.6em;">Testfile</p>
  <table>
    <tr><td><input type="text" id="amount"></input></td><td><button id="payment"></button></td></tr>
    <tr><td></td><td><button id="end_of_day"></button></td></tr>
  </table>
  <p></p>
  <p></p>


<?php echo $menu['end_content']; ?>

</html>
