<!DOCTYPE html>
<html>
<head>
<meta charset='utf-8'/>
<?php
    require_once("../inc/stdLib.php");
    $menu = $_SESSION['menu'];
    $head = mkHeader();
    echo $menu['stylesheets'];
    echo $menu['javascripts'];
    echo $head['THEME'];
    echo $head['JQTABLE'];


?>


<script type="text/javascript">
    $(document).ready(function(){
        $.ajax({
            dataType: "json",
            url: "../jqhelp/getCallList.php?action=complete",
            method: "GET",
            success : function (data){
                //alert("test" + JSON.stringify(data));
                //console.log(data)
                 drawTable(data);
                 $(".tablesorter").tablesorter({
                         sortReset      : true,
                         sortRestart    : true})

            }
        });

        function drawTable(data) {
            for (var i = 0; i < data.length; i++) {
                if (i==0) {
                //$("#tbody").append("")
                }
                drawRow(data[i]);
            }
        }

        function drawRow( rowData ) {
            var row = $("<tr>")
            $("#tbody").append(row);
            row.append($("<td>" + rowData.call_date  + "</td>"));
            row.append($("<td>" + rowData.crmti_status + "</td>"));
            row.append($("<td>" + rowData.crmti_src + "</td>"));
            row.append($("<td>" + rowData.crmti_dst + "</td>"))
            row.append($("<td>" + rowData.crmti_caller_id + "</td>"))
            row.append($("<td>" + rowData.crmti_caller_typ + "</td>"))
            row.append($("<td>" + rowData.crmti_direction + "</td></tr>"))
            }



        $( "#calllist" ).html( "CallList" ).css({
            color: "red"
        })

    });
</script>
<style>
    #calllist    { position:absolute; top:130px; left:87px; }
</style>
</head>
<body>
<?php
    echo $menu['pre_content'];
    echo $menu['start_content'];
?>
<div class="ui-widget-content" style="height:600px">

<table id="DataTable" class="tablesorter">
<thead>
  <tr>
    <th>date</th>
    <th>status</th>
    <th>source</th>
    <th>destination</th>
    <th>caller_id</th>
    <th>caller_typ</th>
    <th>direction</th>
  </tr>
</thead>
<tbody id="tbody">
</tbody>
</table>


<div id="pager"></div>

</div>
<?php echo $menu['end_content']; ?>
</body>
</html>