<!DOCTYPE html>
<html>
<head>
<meta charset='utf-8'/>
<?php
    require_once("../inc/stdLib.php");
    $menu = $_SESSION['menu'];
    $head = mkHeader();
    echo $menu['stylesheets'];
    echo $menu['javascripts'];
    echo $head['JQTABLE'];
    echo $head['THEME'];


?>
<script type="text/javascript">
    $(document).ready(function(){
        $.ajax({
            dataType: "json",
            url: "../jqhelp/call.php?action=getCallListComplete",
            method: "GET",
            success : function (data){
                drawTable(data);
                $("#DataTable").trigger("update");
                $("#DataTable").trigger("appendCache");
            }
        });
        $(document).on("click", "#DataTable tr", function(e) {
            var src = $(this).closest('tr').children().eq(2).text();
            var dst = $(this).closest('tr').children().eq(3).text();
            var id  = $(this).closest('tr').children().eq(4).text();
            var typ = $(this).closest('tr').children().eq(5).text();
            if ( typ == 'X' ){ //Number is not in database
                var number = $.isNumeric( src ) ? src : dst;
                $.ajax({
                    dataType: "json",
                    url: "../jqhelp/call.php?action=numberToAdress&data=" + number,
                    method: "GET",
                    success : function (data){
                        alert("Data: " + JSON.stringify(data));
                    }
               });
            }
            else if( typ == 'K' ) window.location.href = "../kontakt.php?id=" + id;
            else window.location.href = "../firma1.php?Q=" + typ +"&id=" + id;
        });
        function drawTable(data) {
            for (var i = 0; i < data.length; i++) {
                drawRow(data[i]);
            }
        }
        var options = { weekday: 'short', year: 'numeric', month: 'short', day: '2-digit', hour: '2-digit', minute: '2-digit' };
        function drawRow( rowData ) {
            var row = $("<tr>");
            //var row = $("<tr onclick='showD(rowData.crmti_caller_id,rowData.crmti_caller_typ)'>");
            var callDate = new Date( rowData.call_date * 1000 );
            $("#tbody").append(row);
            row.append($("<td>" + callDate.toLocaleDateString('de-DE', options)  + "</td>"));
            row.append($("<td class=>" + rowData.crmti_status + "</td>"));
            row.append($("<td>" + rowData.crmti_src + "</td>"));
            row.append($("<td>" + rowData.crmti_dst + "</td>"))
            row.append($("<td>" + rowData.crmti_caller_id + "</td>"))
            row.append($("<td>" + rowData.crmti_caller_typ + "</td>"))
            row.append($("<td>" + rowData.crmti_direction + "</td></tr>"))
        }
    });

</script>
<style>
  table.tablesorter { width:auto; cursor:pointer; }
  th.date { width: 140px }
  th.status, th.id{ width: 70px }
  th.source, th.dest { width: 200px; }
  th.typ, th.dir { width: 50px; }
</style>
</head>

<body>
<?php
    echo $menu['pre_content'];
    echo $menu['start_content'];
?>
<div class="ui-widget-content" style="height:600px">
<p class="ui-state-highlight ui-corner-all" style="margin-top: 20px; padding: 0.6em;"><b>Anrufliste</b></p>
  <table id="DataTable" class="tablesorter">
    <thead>
      <tr>
        <th class="date">date</th>
        <th class="status">status</th>
        <th class="source">source</th>
        <th class="dest">destination</th>
        <th class="id">caller_id</th>
        <th class="typ">caller_typ</th>
        <th class="dir"> direction</th>
      </tr>
    </thead>
    <tbody id="tbody">
    </tbody>
  </table>
</div>
<?php echo $menu['end_content']; ?>
</body>
</html>