<?php
    /**************************************************************************\    
    * This file was originaly written by Jan Dierolf (jadi75@gmx.de)           *
    * ------------------------------------------------------------------------ *
    *  This program is free software; you can redistribute it and/or modify it *
    *  under the terms of the GNU General Public License as published by the   *
    *  Free Software Foundation; either version 2 of the License, or (at your  *
    *  option) any later version.                                              *
    \**************************************************************************/
 
 $db_map = array( 'id' => 'cp_id',
//'fn' => '',
//'sound' => '',
'org_name' => 'name',
'org_unit' => 'department_1',
'title' => 'cp_title',
'cat_id' => 'categorie',
//'n_prefix' => '',
'n_given' => 'cp_givenname',
//'n_middle' => '',
'n_family' => 'cp_name',
//'n_suffix' => '',
//'label' => 'label',
'adr_one_street' => 'street',
'adr_one_locality' => 'city',
//'adr_one_region' => 'business state',
'adr_one_postalcode' => 'zipcode',
'adr_one_countryname' => 'country',
//'adr_one_type' => '',
'adr_two_street' => 'cp_street',
'adr_two_locality' => 'cp_city',
//'adr_two_region' => 'home state',
'adr_two_postalcode' => 'cp_zipcode',
'adr_two_countryname' => 'cp_country',
//'adr_two_type' => '',
//'tz' => 'time zone',
//'geo' => 'geo',
'tel_work' => 'cp_phone1',
'tel_home' => 'cp_privatphone',
//'tel_voice' => 'voice phone',
//'tel_msg' => 'message phone',
'tel_fax' => 'cp_fax',
//'tel_pager' => 'pager',
'tel_cell' => 'cp_phone2',
//'tel_bbs' => 'bbs phone',
//'tel_modem' => 'modem phone',
//'tel_isdn' => 'isdn phone',
//'tel_car' => 'car phone',
//'tel_video' => 'video phone',
//'tel_prefer' => 'preferred phone',
'email' => 'cp_email',
//'email_type' => 'business email type',
'email_home' => 'cp_privatemail',
//'email_home_type' => 'home email type',
//'address2' => 'address line 2',
//'address3' => 'address line 3',
//'ophone' => 'Other Phone',
'bday' => 'cp_birthday',
'url' => 'cp_homepage',
//'pubkey' => 'public key',
'note' => 'cp_notes' );

////////////////////////////////////////////////////////////////////////////////////////////////
 $db_employee_map = array( 'id' => 'id',
'fn' => 'name',
//'sound' => '',
//'org_name' => 'name',
'org_unit' => 'abteilung',
//'title' => 'cp_title',
'cat_id' => 'categorie',
//'n_prefix' => '',
//'n_given' => 'cp_givenname',
//'n_middle' => '',
//'n_family' => 'cp_name',
//'n_suffix' => '',
//'label' => 'label',
//'adr_one_street' => 'street',
//'adr_one_locality' => 'city',
////'adr_one_region' => 'business state',
//'adr_one_postalcode' => 'zipcode',
//'adr_one_countryname' => 'country',
////'adr_one_type' => '',
//'adr_two_street' => 'cp_street',
//'adr_two_locality' => 'cp_city',
////'adr_two_region' => 'home state',
//'adr_two_postalcode' => 'cp_zipcode',
//'adr_two_countryname' => 'cp_country',
//'adr_two_type' => '',
//'tz' => 'time zone',
//'geo' => 'geo',
'tel_work' => 'workphone',
'tel_home' => 'homephone',
//'tel_voice' => 'voice phone',
//'tel_msg' => 'message phone',
//'tel_fax' => 'fax',
////'tel_pager' => 'pager',
//'tel_cell' => 'cp_mobile1',
//'tel_bbs' => 'bbs phone',
//'tel_modem' => 'modem phone',
//'tel_isdn' => 'isdn phone',
//'tel_car' => 'car phone',
//'tel_video' => 'video phone',
//'tel_prefer' => 'preferred phone',
'email' => 'email',
//'email_type' => 'business email type',
//'email_home' => 'cp_email',
//'email_home_type' => 'home email type',
//'address2' => 'address line 2',
//'address3' => 'address line 3',
//'ophone' => 'Other Phone',
//'bday' => 'birthday',
//'url' => 'cp_homepage',
//'pubkey' => 'public key',
'note' => 'notes' );
?>