#!/bin/sh
#set -x

config_pear() {

	pear upgrade PEAR
	pear=`pear config-get php_dir | cut -d '=' -f 2`
	if [ -f $pear/PEAR.php ]; then 
		#Pear gefunden - updaten
		pear channel-update pear.php.net

		#PEAR-Pakete
		if [ `pear list | grep -c Image_Canvas` -lt 1 ]; then
			# ist nicht installiert
			echo installiere Image_Canvas
		        pear install -f Image_Canvas
		fi
		if ! [ -d /usr/share/php/Image/Canvas/Fonts ]; then
			# ist ne alte Version
			echo update Image_Canvas
			pear install -f Image_Canvas
		fi
		#Font für Umsatzgrafik
		if ! [ -e /usr/share/php/Image/Canvas/Fonts ] ; then
			# Hier gibt es unterschiedliche Versionen
			mkdir /usr/share/php/Image/Canvas/Fonts 2>/dev/null
			touch /usr/share/php/Image/Canvas/Fonts/fontmap.txt
		fi
		if [ `grep -c FreeSans.ttf /usr/share/php/Image/Canvas/Fonts/fontmap.txt` -lt 1 ]; then
			echo Font einbinden
		    	ln /usr/share/fonts/truetype/freefont/FreeSans.ttf /usr/share/php/Image/Canvas/Fonts/FreeSans.ttf
		    	echo "FreeSans,FreeSans.ttf" >> /usr/share/php/Image/Canvas/Fonts/fontmap.txt
		fi
		if [ `pear list | grep -c Image_Color` -lt 1 ]; then
			echo installiere Image_Color
			pear install Image_Color
		fi
		if [ `pear list | grep -c Image_Graph` -lt 1 ]; then
			echo installiere Image_Graph
			pear install -f Image_Graph
		fi
		if [ `pear list | grep -c Contact_Vcard_Build` -lt 1 ]; then
			echo installiere Contact_Vcard_Build
			pear install Contact_Vcard_Build
		fi
		if [ `pear list | grep -c Contact_Vcard_Parse` -lt 1 ]; then
			echo installiere Contact_Vcard_Parse
			pear install Contact_Vcard_Parse
		fi
	else
		echo "PEAR nicht gefunden"
		echo "Bitte uU folgende Pakete installieren:"
		echo "Image_Canvas Image_Color Image_Graph Contact_Vcard_Build Contact_Vcard_Parse"
	fi
}

config_xajax() {
	Xver=`dpkg -l php-xajax 2>/dev/null | grep "ii " | cut -d. -f2`
	XAJAX=0
	if [ $Xver == "2" ]; then
		#Xajax einhängen
		if ! [ -e /usr/lib/lx-office-crm/crmajax/xajax ] ; then
		    ln -s /usr/share/php/xajax/ /usr/lib/lx-office-crm/crmajax/xajax
		    XAJAX=1
		fi
	elif [ $Xver == "5" ]; then
		#Xajax einhängen
		if ! [ -e /usr/lib/lx-office-crm/crmajax/xajax_core ] ; then
		    ln -s /usr/share/php/xajax_core/ /usr/lib/lx-office-crm/crmajax/xajax_core
		    ln -s /usr/share/php/xajax_js/ /usr/lib/lx-office-crm/crmajax/xajax_js
		    XAJAX=1
		fi
	fi
	#Xajax nicht eingehängt
	if   [ $XAJAX == "0" ] ;then
		db_get lx-office-crm/xajaxerr
	fi
}


config_link() {
	#CRM in ERP einhängen
	if [ -L /usr/lib/lx-office-erp/crm ]; then
		#alten Link entfernen
		rm /usr/lib/lx-office-erp/crm
		ln -s /usr/lib/lx-office-crm /usr/lib/lx-office-erp/crm
	elif [ -d /usr/lib/lx-office-erp/crm ]; then
		#crm ist ein Unterverzeichnis, umbenennen
		mv /usr/lib/lx-office-erp/crm /usr/lib/lx-office-erp/crm_
		ln -s /usr/lib/lx-office-crm /usr/lib/lx-office-erp/crm
		#alte, bestehende Vorlagen und Dokumente umkopieren
		cp -ar /usr/lib/lx-office-erp/crm_/vorlage/* /usr/lib/lx-office-erp/crm/vorlage/
		cp -ar /usr/lib/lx-office-erp/crm_/dokumente/* /usr/lib/lx-office-erp/crm/dokumente/
	else
		#ist noch nicht drin
		ln -s /usr/lib/lx-office-crm /usr/lib/lx-office-erp/crm
	fi

	rm /usr/lib/lx-office-erp/image/CRM.png 2>/dev/null
	ln -s /usr/lib/lx-office-crm/image/CRM.png /usr/lib/lx-office-erp/image/CRM.png
}

config_menu() {
	#Menu anpassen
	echo "ERP-Menue wird angepasst"
	if ! [ -f /usr/lib/lx-office-erp/crm_menu.ini ]; then
	    #Noch keine Sicherheitskopie vom Original erstellt.
	    cp /usr/lib/lx-office-erp/menu.ini /usr/lib/lx-office-erp/crm_menu.ini  
	fi

	cnt=`grep -c CRM /usr/lib/lx-office-erp/menu.ini`

	if [ $cnt == 0 ]; then
	  if  [ -f /usr/lib/lx-office-erp/menu.default ]; then
	    cat /usr/lib/lx-office-crm/update/menu.ini /usr/lib/lx-office-erp/menu.default > /usr/lib/lx-office-erp/menu.ini
	  elif  [ -f /usr/lib/lx-office-erp/crm_menu.ini ]; then
	    cat /usr/lib/lx-office-crm/update/menu.ini /usr/lib/lx-office-erp/crm_menu.ini > /usr/lib/lx-office-erp/menu.ini
	  fi
        else
	    patch -u -N /usr/lib/lx-office-erp/menu.ini /usr/lib/lx-office-crm/update/menu142.patch
	fi
	chown www-data: /usr/lib/lx-office-erp/menu.ini
}


config_conf() {
	if ! [ -e /usr/lib/lx-office-crm/inc/conf.php ]; then
	    cp /usr/lib/lx-office-crm/inc/conf.php.default /usr/lib/lx-office-crm/inc/conf.php
	else
	    # vorhanden, VERSION entfernen und dann zurücksichern.
	    mv /usr/lib/lx-office-crm/inc/conf.php /usr/lib/lx-office-crm/inc/conf.php.org
	    grep -v VERSION /usr/lib/lx-office-crm/inc/conf.php.org > /usr/lib/lx-office-crm/inc/conf.php
	    cat /usr/lib/lx-office-crm/update/conf142.php >> /usr/lib/lx-office-crm/inc/conf.php
	fi

	if [ `grep -c CallEdit /usr/lib/lx-office-crm/inc/conf.php` -lt 1 ]; then
		echo "<?php" >> /usr/lib/lx-office-crm/inc/conf.php;
		echo "\$showErr = false;" >> /usr/lib/lx-office-crm/inc/conf.php;
		echo "\$logmail = true;" >> /usr/lib/lx-office-crm/inc/conf.php;
		echo "\$jcalendar = true;" >> /usr/lib/lx-office-crm/inc/conf.php;
		echo "\$listLimit = 500;" >> /usr/lib/lx-office-crm/inc/conf.php;
		echo "\$tinymce = false;" >> /usr/lib/lx-office-crm/inc/conf.php;
		echo "\$CallEdit = true;" >> /usr/lib/lx-office-crm/inc/conf.php;
		echo "\$CallDel = true;" >> /usr/lib/lx-office-crm/inc/conf.php;
		echo "?>" >> /usr/lib/lx-office-crm/inc/conf.php;
	fi

	if [ `grep -c GEODB /usr/lib/lx-office-crm/inc/conf.php` -lt 1 ]; then
		echo "<?php" >> /usr/lib/lx-office-crm/inc/conf.php;
		echo "\$GEODB = false;" >> /usr/lib/lx-office-crm/inc/conf.php;
		echo "\$BLZDB = false;" >> /usr/lib/lx-office-crm/inc/conf.php;
		echo "?>" >> /usr/lib/lx-office-crm/inc/conf.php;
	fi

	if [ `grep -c dbmodul /usr/lib/lx-office-crm/inc/conf.php` -lt 1 ]; then
	    echo "<?php" >> /usr/lib/lx-office-crm/inc/conf.php;
	    echo "\dbmodul=\"\";" >> /usr/lib/lx-office-crm/inc/conf.php;
	    echo "define(\"XajaxVer\",\"\");" >> /usr/lib/lx-office-crm/inc/conf.php;
	    echo "define(\"XajaxPath\",\"./crmajax/xajax\");" >> /usr/lib/lx-office-crm/inc/conf.php;
		echo "?>" >> /usr/lib/lx-office-crm/inc/conf.php;
	fi

	if [ `grep -c MailFlag /usr/lib/lx-office-crm/inc/conf.php` -lt 1 ]; then
		echo "<?php" >> /usr/lib/lx-office-crm/inc/conf.php;
		echo "\$Expunge=True;" >> /usr/lib/lx-office-crm/inc/conf.php;
		echo "\$MailFlag=\"Flagged\";" >> /usr/lib/lx-office-crm/inc/conf.php;
		echo "\$ttpart=\"\";" >> /usr/lib/lx-office-crm/inc/conf.php;
		echo "\$tttime=60;" >> /usr/lib/lx-office-crm/inc/conf.php;
		echo "\$ttround=15;" >> /usr/lib/lx-office-crm/inc/conf.php;
		echo "?>" >> /usr/lib/lx-office-crm/inc/conf.php;
	fi
	chown www-data: /usr/lib/lx-office-crm/inc/conf.php
}

case "$1" in

    upgrade)
        echo " ! "`date`" $1 !" >> /tmp/lxo-erp.log
	config_menu
	config_conf
    ;;

    install|configure)
        echo " ! "`date`" $1 !" >> /tmp/lxo-erp.log
	config_pear
	config_xajax
	config_link
	config_menu
	config_conf

    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

echo "done!!"

exit 0
