#!/bin/sh
set -e

case "$1" in
    remove|deconfigure)
	rm /usr/lib/lx-office-erp/crm
	mv /usr/lib/lx-office-erp/crm_menu.ini /usr/lib/lx-office-erp/menu.ini
	rm /usr/lib/lx-office-erp/image/CRM.png
	rm -rf /var/lib/lx-office-crm/dokumente
	rm -rf /var/lib/lx-office-crm/vorlage
        ;;
    upgrade)
        ;;
    failed-upgrade)
        ;;
    *)
        echo "prerm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

